import requests
import json
import os

TOKEN = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjE2ZWUwMzFlODZhM2YwZmNkOWI2ZDcwMDJiMDJiMDg2ZDJmNTVkZTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcGxhY2VtZW50ZGF0YS1iM2RiNyIsImF1ZCI6InBsYWNlbWVudGRhdGEtYjNkYjciLCJhdXRoX3RpbWUiOjE3ODUyNTU2ODgsInVzZXJfaWQiOiJLUEZsVUhjdDVpU2VEQjVVNVBOZXdEUVpCRHIxIiwic3ViIjoiS1BGbFVIY3Q1aVNlREI1VTVQTmV3RFFaQkRyMSIsImlhdCI6MTc4NTI1NTY4OCwiZXhwIjoxNzg1MjU5Mjg4LCJlbWFpbCI6Im1iaHVsbGFyX2JlMjNAdGhhcGFyLmVkdSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1iaHVsbGFyX2JlMjNAdGhhcGFyLmVkdSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.iUiGBriWYlQfinUAyW3YuomGCsKwASC6Nfjwb41HpH7K5AI-FrR7kJDrWY2732Nerza6Ztf_SGGTBbENb3ZDvxeBD7u8NBlUE5T8nBG5eLL8C3BMSx5YAjE21BQf6uzai1ZS-dCYI3hHFCvuMxCZFNx1_3EtLwiVK8PcPgJA6pIH_VLuvmIRyE9NELPg0NRJd0noYI2uprtsS_AbuKdoA5zi1TzSPGlRm5LE1VeD7KX5XoAZ2MTnWcNnowYkNenXwBiQ-2u3_LQG0cjxvw4M4_UieJpJWr9x7V0MtHOZvHbCAy8LEgyskSkMF0FWgBsjZ9QDqbD0TUgfp-3GSuYnHw"
PROJECT_ID = "placementdata-b3db7"
URL = f"https://firestore.googleapis.com/v1/projects/{PROJECT_ID}/databases/(default)/documents:listCollectionIds"

headers = {
    "Authorization": f"Bearer {TOKEN}"
}

res = requests.post(URL, headers=headers, json={})
print("Collections:", res.json())
